version: '3'
services:

  flask:
    build: .
    container_name: flask-container
    ports:
      - "5000:5000"
    depends_on:
      - redis


  redis:
    image: redis
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./redisdata:/data


  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis


  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGODB_HOST: mongodb
    ports:
      - 27017:27017
    volumes:
      - ./mongodata:/data/db

volumes:
  redisdata:
  mongodata: